enabled: true
favicon:
  user/themes/big-picture/images/favicon.png:
    name: favicon.png
    type: image/png
    size: 1610
    path: user/themes/big-picture/images/favicon.png
error_background_image: {  }
